# Initialized `__init__.py` generated by ipm.
# This is the entry file for this Infini package.# Documents at https://ipm.hydroroll.team/

from .events import register as events_register
from .handlers import register as handlers_register
from .interceptors import register as interceptors_register

from infini.internal import require

ndice_register = require("ndice")
